apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalsandbox-deployment
  labels:
    app: finalsandboxi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finalsandbox
  template:
    metadata:
      labels:
        app: finalsandbox
    spec:
      containers:
      - name: finalsandbox
        image: 660600267212.dkr.ecr.eu-north-1.amazonaws.com/finalsandbox:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
