apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simple-cluster
  region: eu-north-1
  version: '1.22'

nodeGroups:
  - name: ng-1
    instanceType: t3.micro
    desiredCapacity: 3
    privateNetworking: true
    labels: { tier: new }
